# Generated by Django 5.2.10 on 2026-02-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_insurancepolicy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bedbooking",
            name="payment_option",
            field=models.CharField(
                choices=[
                    ("CASH", "Cash at Hospital"),
                    ("INSURANCE", "Insurance / TPA"),
                    ("WALLET", "Pay with Wallet"),
                ],
                default="CASH",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="oxygenbooking",
            name="payment_option",
            field=models.CharField(
                choices=[
                    ("CASH", "Pay at Hospital"),
                    ("INSURANCE", "Insurance / TPA"),
                    ("WALLET", "Pay with Wallet"),
                ],
                default="CASH",
                max_length=20,
            ),
        ),
    ]
