# Generated by Django 5.2.10 on 2026-02-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_alter_bedbooking_payment_option_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="payment_option",
            field=models.CharField(
                choices=[
                    ("CASH", "Pay at Clinic"),
                    ("INSURANCE", "Insurance / TPA"),
                    ("WALLET", "Pay with Wallet"),
                ],
                default="CASH",
                max_length=20,
            ),
        ),
    ]
