# Generated by Django 5.2.8 on 2026-02-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_appointment_payment_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='bedbooking',
            name='prescription',
            field=models.FileField(blank=True, help_text='Doctor prescription (PDF/JPG/PNG, Max 5MB)', null=True, upload_to='prescriptions/'),
        ),
        migrations.AlterField(
            model_name='bedbooking',
            name='status',
            field=models.CharField(choices=[('AWAITING_PAYMENT', 'Awaiting Payment'), ('PENDING', 'Pending Admin Approval'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='AWAITING_PAYMENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='hospitalbed',
            name='bed_type',
            field=models.CharField(choices=[('ICU', 'Deluxe Bed'), ('GENERAL', 'General'), ('EMERGENCY', 'Emergency')], max_length=20),
        ),
    ]
