# Generated by Django

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_bedbooking_prescription_alter_bedbooking_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='consultation_fee',
            new_name='fees',
        ),
    ]
